acrName: "containerregistrymcherfi"
imageTag: "latest"
namespace: "malik-cherfi"

db:
  host: ""
  user: ""
  name: "psql_database"
  password: ""

redis:
  host: ""
  port: 10000 # Azure Managed Redis's default port ( REDIS_SSL_ENABLED: true)
  password: ""
  sslEnabled: "true"

app:
  apiKey: ""
  storage:
    accountName: ""
    containerName: ""
    sasToken: ""
